# Generated by Django 4.1.7 on 2023-02-22 14:37

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='Give_Your_Valuable_Feedback',
            field=models.CharField(default='feedback', max_length=200),
        ),
        migrations.AddField(
            model_name='form',
            name='Rate_our_products_and_service',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], default='-----', max_length=15),
        ),
        migrations.AddField(
            model_name='form',
            name='email',
            field=models.EmailField(default='@mail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='form',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+919012345678', max_length=128, region=None, unique=True),
        ),
    ]
