# Generated by Django 4.1.7 on 2023-02-22 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_alter_form_give_your_valuable_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='Rate_our_products_and_service',
            new_name='Rate_our_Internship_and_services',
        ),
    ]
